// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: characters.sql

package database

import (
	"context"
)

const addCharacter = `-- name: AddCharacter :one
INSERT INTO characters (id, value, created_at, updated_at, word_id)
VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?)
RETURNING id, value, created_at, updated_at, word_id
`

type AddCharacterParams struct {
	ID     interface{}
	Value  interface{}
	WordID interface{}
}

func (q *Queries) AddCharacter(ctx context.Context, arg AddCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, addCharacter, arg.ID, arg.Value, arg.WordID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WordID,
	)
	return i, err
}
