// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package database

import (
	"context"
)

const addDocument = `-- name: AddDocument :one
INSERT INTO documents (id, name, created_at, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, created_at, updated_at
`

type AddDocumentParams struct {
	ID   interface{}
	Name string
}

func (q *Queries) AddDocument(ctx context.Context, arg AddDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, addDocument, arg.ID, arg.Name)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDocumentBYName = `-- name: FindDocumentBYName :one
SELECT id, name, created_at, updated_at FROM documents
WHERE name=?
`

func (q *Queries) FindDocumentBYName(ctx context.Context, name string) (Document, error) {
	row := q.db.QueryRowContext(ctx, findDocumentBYName, name)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
