// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Character struct {
	ID        interface{}
	Value     interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	WordID    interface{}
}

type Document struct {
	ID        interface{}
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Word struct {
	ID         interface{}
	Value      string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DocumentID interface{}
}
