// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: words.sql

package database

import (
	"context"
)

const addWord = `-- name: AddWord :one
INSERT INTO words (id, value, created_at, updated_at, document_id)
VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?)
RETURNING id, value, created_at, updated_at, document_id
`

type AddWordParams struct {
	ID         interface{}
	Value      string
	DocumentID interface{}
}

func (q *Queries) AddWord(ctx context.Context, arg AddWordParams) (Word, error) {
	row := q.db.QueryRowContext(ctx, addWord, arg.ID, arg.Value, arg.DocumentID)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DocumentID,
	)
	return i, err
}

const countWordsFrequencies = `-- name: CountWordsFrequencies :many
SELECT value AS word, COUNT(*) AS freq
FROM words
WHERE document_id = ?
GROUP BY value
ORDER BY freq DESC
LIMIT 25
`

type CountWordsFrequenciesRow struct {
	Word string
	Freq int64
}

func (q *Queries) CountWordsFrequencies(ctx context.Context, documentID interface{}) ([]CountWordsFrequenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, countWordsFrequencies, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountWordsFrequenciesRow
	for rows.Next() {
		var i CountWordsFrequenciesRow
		if err := rows.Scan(&i.Word, &i.Freq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
